/** 守护脚本参数（主进程写 guardian-params.json，UTF-8；路径可含非 ASCII） */
export interface GuardianParams {
  /** 已下载校验通过的安装包绝对路径（支持 .exe NSIS 或 .msi） */
  setupPath: string
  /** 当前应用 exe 绝对路径（其目录即安装目录/备份源） */
  exePath: string
  statePath: string
  /** 备份目标目录（如 .../updates/backup-0.1.0） */
  backupDir: string
  logPath: string
  fromVersion: string
  toVersion: string
}

/**
 * 生成纯 ASCII 的 PowerShell 5.1 守护脚本。
 * 流程：等应用退出 → 必要时自我提权（UAC 一次）→ robocopy 备份安装目录
 *      → 静默安装（NSIS /S 或 msiexec /qn）→ 校验新版本 → 成功启动新版；
 *      失败 robocopy /MIR 回滚并启动旧版。
 * 所有路径运行时从同目录 guardian-params.json 读取，脚本内不硬编码任何路径。
 */
export function buildGuardianScript(): string {
  return String.raw`# TemplatePrint update guardian (ASCII only). Generated by the app - do not edit.
param([switch]$Elevated)
$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path $MyInvocation.MyCommand.Path -Parent
$params = Get-Content (Join-Path $scriptDir 'guardian-params.json') -Encoding UTF8 -Raw | ConvertFrom-Json
$logFile = $params.logPath
$installDir = Split-Path $params.exePath -Parent

function Write-Log($m) {
  $line = (Get-Date).ToString('s') + ' ' + $m
  Out-File -FilePath $logFile -Append -Encoding ASCII -InputObject $line
}
function Write-GuardianState($phase, $reason) {
  $o = [ordered]@{
    from = $params.fromVersion
    to = $params.toVersion
    phase = $phase
    reason = $reason
    ts = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
  }
  ($o | ConvertTo-Json -Compress) | Out-File -FilePath $params.statePath -Encoding ASCII
}
function Test-MinVersion($actual, $min) {
  if (-not $actual) { return $false }
  $a = $actual.Split('.')
  $b = $min.Split('.')
  for ($i = 0; $i -lt [Math]::Max($a.Length, $b.Length); $i++) {
    $x = 0; $y = 0
    if ($i -lt $a.Length) { [void][int]::TryParse(($a[$i] -replace '[^0-9].*$',''), [ref]$x) }
    if ($i -lt $b.Length) { [void][int]::TryParse(($b[$i] -replace '[^0-9].*$',''), [ref]$y) }
    if ($x -lt $y) { return $false }
    if ($x -gt $y) { return $true }
  }
  return $true
}
function Start-App() {
  # ShellExecute launches at normal integrity (avoid inheriting elevated guardian token)
  $shell = New-Object -ComObject Shell.Application
  $shell.ShellExecute($params.exePath)
}
function Fail-Guardian($code) {
  Write-Log ('FAIL ' + $code)
  try { Write-GuardianState 'failed' $code } catch { Write-Log ('state-write-failed ' + $_.Exception.Message) }
  try {
    if (Test-Path $params.backupDir) {
      Write-Log 'rollback with robocopy /MIR'
      robocopy $params.backupDir $installDir /MIR /R:1 /W:1 /NFL /NDL /NJH /NJS /NP | Out-Null
      Write-Log ('rollback exit ' + $LASTEXITCODE)
    }
  } catch { Write-Log ('rollback-failed ' + $_.Exception.Message) }
  Start-App
  exit 1
}

if (-not $Elevated) {
  # 1) Wait for the app to exit (match by absolute exe path; guardian lives in updates dir)
  $deadline = (Get-Date).AddSeconds(60)
  while ((Get-Date) -lt $deadline) {
    $running = @(Get-Process | Where-Object {
      try { $_.Path -and ($_.Path -eq $params.exePath) } catch { $false }
    })
    if ($running.Count -eq 0) { break }
    Start-Sleep -Milliseconds 500
  }
  $still = @(Get-Process | Where-Object {
    try { $_.Path -and ($_.Path -eq $params.exePath) } catch { $false }
  })
  if ($still.Count -gt 0) { Fail-Guardian 'wait-process-timeout' }

  # 2) Probe write access to install dir; self-elevate (single UAC) if required
  $probe = Join-Path $installDir ('.tp-write-probe-' + [Guid]::NewGuid().ToString('N'))
  $needAdmin = $false
  try {
    New-Item -ItemType File -Path $probe -Force | Out-Null
    Remove-Item $probe -Force
  } catch { $needAdmin = $true }
  if ($needAdmin) {
    Write-Log 'elevating'
    Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList @(
      '-ExecutionPolicy', 'Bypass', '-WindowStyle', 'Hidden', '-File', $PSCommandPath, '-Elevated'
    )
    exit 0
  }
}

try {
  Write-Log ('guardian start ' + $params.fromVersion + ' -> ' + $params.toVersion)
  New-Item -ItemType Directory -Force -Path (Split-Path $params.statePath -Parent) | Out-Null
  New-Item -ItemType Directory -Force -Path (Split-Path $params.logPath -Parent) | Out-Null
  Write-GuardianState 'installing' $null

  # 3) Back up current install directory
  New-Item -ItemType Directory -Force -Path $params.backupDir | Out-Null
  robocopy $installDir $params.backupDir /E /R:1 /W:1 /NFL /NDL /NJH /NJS /NP | Out-Null
  if ($LASTEXITCODE -gt 7) { Fail-Guardian 'backup-failed' }
  Write-Log ('backup exit ' + $LASTEXITCODE)

  # 4) Silent install - explicitly target the current install directory.
  #    NSIS (.exe): /S + /D=<dir> (NSIS rule: /D must be LAST arg, path NOT quoted).
  #    MSI  (.msi): msiexec /i <pkg> INSTALLDIR="<dir>" /qn /norestart
  #                 exit 0 = OK, 3010 = OK restart-required.
  #    Without an explicit target dir the installer may use its default location
  #    (especially after self-elevation changes the registry hive), leaving the
  #    old exe untouched -> verify-failed -> rollback.
  $ext = [System.IO.Path]::GetExtension($params.setupPath).ToLowerInvariant()
  if ($ext -eq '.msi') {
    $msiArgs = '/i "' + $params.setupPath + '" INSTALLDIR="' + $installDir + '" /qn /norestart'
    $p = Start-Process -FilePath 'msiexec.exe' -ArgumentList $msiArgs -Wait -PassThru
    Write-Log ('installer exit ' + $p.ExitCode)
    if ($p.ExitCode -ne 0 -and $p.ExitCode -ne 3010) { Fail-Guardian 'installer-failed' }
  } else {
    $p = Start-Process -FilePath $params.setupPath -ArgumentList "/S /D=$installDir" -Wait -PassThru
    Write-Log ('installer exit ' + $p.ExitCode)
    if ($p.ExitCode -ne 0) { Fail-Guardian 'installer-failed' }
  }

  # 5) Verify new version
  if (-not (Test-Path $params.exePath)) { Fail-Guardian 'verify-failed' }
  $actual = (Get-Item $params.exePath).VersionInfo.ProductVersion
  Write-Log ('new version ' + $actual)
  if (-not (Test-MinVersion $actual $params.toVersion)) { Fail-Guardian 'verify-failed' }

  Write-GuardianState 'done' $null
  Write-Log 'done'
  Start-App
  exit 0
} catch {
  Write-Log ('exception ' + $_.Exception.Message)
  Fail-Guardian 'installer-failed'
}
`
}
